Implemented a number converter with tests
software-students-fall2022/python-package-exercise-project-3-team-10 pull request #6
Opened 2022-11-05 06:47 UTC by junyid

2022-11-07 19:17 UTC, JonasonWu requested changes
Add test of conversion to self (i.e., binary to binary, octal to octal, etc.)

2022-11-07 19:26 UTC, junyid commented
Added more test cases.

2022-11-08 04:42 UTC, aleolazabal approved these changes
looks good

2022-11-08 04:43 UTC, aleolazabal approved these changes

2022-11-08 12:48 UTC, JonasonWu approved these changes

2022-11-08 15:48 UTC, aleolazabal approved these changes

2022-11-08 15:49 UTC, merged